services:
  - type: web
    name: api-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 4 -b 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        value: <localhost>
      - key: DB_USER
        value: <root>
      - key: DB_PASSWORD
        value: <bil18a>
      - key: DB_NAME
        value: <msg18>
